branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: MediaMeet-backend2
  branch: null
  default_ec2_keyname: arep
  default_platform: Java 8 running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
